use crate::text::AtlasSignature;

use super::buffer::WgpuBuffer;

mod bindings;
mod upload;
mod work_buffers;

pub(crate) use bindings::{
    WgpuCoarseBindings, WgpuCumsumBindings, WgpuFilterBindings, WgpuScanBindings,
    WgpuTileFineBindings,
};
pub(crate) use upload::WgpuSceneUploadStaging;
pub(crate) use work_buffers::{WgpuCoarseBuffers, WgpuScanBuffers};
pub(crate) struct WgpuSceneBuffers {
    line_path_ids: WgpuBuffer,
    line_p0x: WgpuBuffer,
    line_p0y: WgpuBuffer,
    line_p1x: WgpuBuffer,
    line_p1y: WgpuBuffer,
    path_flags: WgpuBuffer,
    draw_path_ids: WgpuBuffer,
    draw_glyph_run_ids: WgpuBuffer,
    draw_glyph_run_ids_without_text: WgpuBuffer,
    draw_flags: WgpuBuffer,
    draw_flags_without_text: WgpuBuffer,
    draw_brush_colors: WgpuBuffer,
    draw_pixel_x0: WgpuBuffer,
    draw_pixel_y0: WgpuBuffer,
    draw_pixel_x1: WgpuBuffer,
    draw_pixel_y1: WgpuBuffer,
    sdf_refs: WgpuBuffer,
    sdf_kinds: WgpuBuffer,
    sdf_x0: WgpuBuffer,
    sdf_y0: WgpuBuffer,
    sdf_x1: WgpuBuffer,
    sdf_y1: WgpuBuffer,
    sdf_r0: WgpuBuffer,
    sdf_r1: WgpuBuffer,
    sdf_r2: WgpuBuffer,
    sdf_r3: WgpuBuffer,
    sdf_stroke_top: WgpuBuffer,
    sdf_stroke_right: WgpuBuffer,
    sdf_stroke_bottom: WgpuBuffer,
    sdf_stroke_left: WgpuBuffer,
    sdf_shadow_offset_x: WgpuBuffer,
    sdf_shadow_offset_y: WgpuBuffer,
    sdf_shadow_expand: WgpuBuffer,
    sdf_shadow_intensity: WgpuBuffer,
    backdrop_data_offsets: WgpuBuffer,
    backdrop_data_lens: WgpuBuffer,
    backdrop_tile_x0: WgpuBuffer,
    backdrop_tile_y0: WgpuBuffer,
    backdrop_tile_x1: WgpuBuffer,
    backdrop_tile_y1: WgpuBuffer,
    backdrop_segment_starts: WgpuBuffer,
    backdrop_segment_capacities: WgpuBuffer,
    scan_chunk_path_ids: WgpuBuffer,
    scan_chunk_backdrop_offsets: WgpuBuffer,
    scan_chunk_segment_starts: WgpuBuffer,
    scan_chunk_lens: WgpuBuffer,
    scan_chunk_range_starts: WgpuBuffer,
    scan_chunk_range_ends: WgpuBuffer,
    cumsum_chunk_backdrop_offsets: WgpuBuffer,
    cumsum_chunk_lens: WgpuBuffer,
    cumsum_row_chunk_starts: WgpuBuffer,
    cumsum_row_chunk_ends: WgpuBuffer,
    tile_draw_range_starts: WgpuBuffer,
    tile_draw_range_ends: WgpuBuffer,
    tile_draw_indices: WgpuBuffer,
    plan_layer_stack_tags: WgpuBuffer,
    plan_layer_stack_draws: WgpuBuffer,
    plan_layer_stack_payloads: WgpuBuffer,
    draw_brush_data: WgpuBuffer,
    draw_brush_params: WgpuBuffer,
    draw_brush_payloads: WgpuBuffer,
    text_run_starts: WgpuBuffer,
    text_run_counts: WgpuBuffer,
    glyph_image_ids: WgpuBuffer,
    glyph_x: WgpuBuffer,
    glyph_y: WgpuBuffer,
    glyph_image_left: WgpuBuffer,
    glyph_image_top: WgpuBuffer,
    glyph_image_width: WgpuBuffer,
    glyph_image_height: WgpuBuffer,
    glyph_image_content: WgpuBuffer,
    glyph_image_data_offsets: WgpuBuffer,
    glyph_image_data: WgpuBuffer,
    glyph_atlas_signature: AtlasSignature,
}

impl WgpuSceneBuffers {
    pub(crate) fn new(device: &::wgpu::Device) -> Self {
        Self {
            line_path_ids: WgpuBuffer::new(device, "tileink wgpu canvas line path ids"),
            line_p0x: WgpuBuffer::new(device, "tileink wgpu canvas line p0x"),
            line_p0y: WgpuBuffer::new(device, "tileink wgpu canvas line p0y"),
            line_p1x: WgpuBuffer::new(device, "tileink wgpu canvas line p1x"),
            line_p1y: WgpuBuffer::new(device, "tileink wgpu canvas line p1y"),
            path_flags: WgpuBuffer::new(device, "tileink wgpu canvas path flags"),
            draw_path_ids: WgpuBuffer::new(device, "tileink wgpu canvas draw path ids"),
            draw_glyph_run_ids: WgpuBuffer::new(device, "tileink wgpu canvas draw glyph run ids"),
            draw_glyph_run_ids_without_text: WgpuBuffer::new(
                device,
                "tileink wgpu canvas draw glyph run ids without text",
            ),
            draw_flags: WgpuBuffer::new(device, "tileink wgpu canvas draw flags"),
            draw_flags_without_text: WgpuBuffer::new(
                device,
                "tileink wgpu canvas draw flags without text",
            ),
            draw_brush_colors: WgpuBuffer::new(device, "tileink wgpu canvas draw brush colors"),
            draw_pixel_x0: WgpuBuffer::new(device, "tileink wgpu canvas draw pixel x0"),
            draw_pixel_y0: WgpuBuffer::new(device, "tileink wgpu canvas draw pixel y0"),
            draw_pixel_x1: WgpuBuffer::new(device, "tileink wgpu canvas draw pixel x1"),
            draw_pixel_y1: WgpuBuffer::new(device, "tileink wgpu canvas draw pixel y1"),
            sdf_refs: WgpuBuffer::new(device, "tileink wgpu canvas sdf refs"),
            sdf_kinds: WgpuBuffer::new(device, "tileink wgpu canvas sdf kinds"),
            sdf_x0: WgpuBuffer::new(device, "tileink wgpu canvas sdf x0"),
            sdf_y0: WgpuBuffer::new(device, "tileink wgpu canvas sdf y0"),
            sdf_x1: WgpuBuffer::new(device, "tileink wgpu canvas sdf x1"),
            sdf_y1: WgpuBuffer::new(device, "tileink wgpu canvas sdf y1"),
            sdf_r0: WgpuBuffer::new(device, "tileink wgpu canvas sdf r0"),
            sdf_r1: WgpuBuffer::new(device, "tileink wgpu canvas sdf r1"),
            sdf_r2: WgpuBuffer::new(device, "tileink wgpu canvas sdf r2"),
            sdf_r3: WgpuBuffer::new(device, "tileink wgpu canvas sdf r3"),
            sdf_stroke_top: WgpuBuffer::new(device, "tileink wgpu canvas sdf stroke top"),
            sdf_stroke_right: WgpuBuffer::new(device, "tileink wgpu canvas sdf stroke right"),
            sdf_stroke_bottom: WgpuBuffer::new(device, "tileink wgpu canvas sdf stroke bottom"),
            sdf_stroke_left: WgpuBuffer::new(device, "tileink wgpu canvas sdf stroke left"),
            sdf_shadow_offset_x: WgpuBuffer::new(device, "tileink wgpu canvas sdf shadow offset x"),
            sdf_shadow_offset_y: WgpuBuffer::new(device, "tileink wgpu canvas sdf shadow offset y"),
            sdf_shadow_expand: WgpuBuffer::new(device, "tileink wgpu canvas sdf shadow expand"),
            sdf_shadow_intensity: WgpuBuffer::new(
                device,
                "tileink wgpu canvas sdf shadow intensity",
            ),
            backdrop_data_offsets: WgpuBuffer::new(
                device,
                "tileink wgpu canvas backdrop data offsets",
            ),
            backdrop_data_lens: WgpuBuffer::new(device, "tileink wgpu canvas backdrop data lens"),
            backdrop_tile_x0: WgpuBuffer::new(device, "tileink wgpu canvas backdrop tile x0"),
            backdrop_tile_y0: WgpuBuffer::new(device, "tileink wgpu canvas backdrop tile y0"),
            backdrop_tile_x1: WgpuBuffer::new(device, "tileink wgpu canvas backdrop tile x1"),
            backdrop_tile_y1: WgpuBuffer::new(device, "tileink wgpu canvas backdrop tile y1"),
            backdrop_segment_starts: WgpuBuffer::new(
                device,
                "tileink wgpu canvas backdrop segment starts",
            ),
            backdrop_segment_capacities: WgpuBuffer::new(
                device,
                "tileink wgpu canvas backdrop segment capacities",
            ),
            scan_chunk_path_ids: WgpuBuffer::new(device, "tileink wgpu canvas scan chunk path ids"),
            scan_chunk_backdrop_offsets: WgpuBuffer::new(
                device,
                "tileink wgpu canvas scan chunk backdrop offsets",
            ),
            scan_chunk_segment_starts: WgpuBuffer::new(
                device,
                "tileink wgpu canvas scan chunk segment starts",
            ),
            scan_chunk_lens: WgpuBuffer::new(device, "tileink wgpu canvas scan chunk lens"),
            scan_chunk_range_starts: WgpuBuffer::new(
                device,
                "tileink wgpu canvas scan chunk range starts",
            ),
            scan_chunk_range_ends: WgpuBuffer::new(
                device,
                "tileink wgpu canvas scan chunk range ends",
            ),
            cumsum_chunk_backdrop_offsets: WgpuBuffer::new(
                device,
                "tileink wgpu canvas cumsum chunk backdrop offsets",
            ),
            cumsum_chunk_lens: WgpuBuffer::new(device, "tileink wgpu canvas cumsum chunk lens"),
            cumsum_row_chunk_starts: WgpuBuffer::new(
                device,
                "tileink wgpu canvas cumsum row chunk starts",
            ),
            cumsum_row_chunk_ends: WgpuBuffer::new(
                device,
                "tileink wgpu canvas cumsum row chunk ends",
            ),
            tile_draw_range_starts: WgpuBuffer::new(
                device,
                "tileink wgpu canvas tile draw range starts",
            ),
            tile_draw_range_ends: WgpuBuffer::new(
                device,
                "tileink wgpu canvas tile draw range ends",
            ),
            tile_draw_indices: WgpuBuffer::new(device, "tileink wgpu canvas tile draw indices"),
            plan_layer_stack_tags: WgpuBuffer::new(
                device,
                "tileink wgpu canvas plan layer stack tags",
            ),
            plan_layer_stack_draws: WgpuBuffer::new(
                device,
                "tileink wgpu canvas plan layer stack draws",
            ),
            plan_layer_stack_payloads: WgpuBuffer::new(
                device,
                "tileink wgpu canvas plan layer stack payloads",
            ),
            draw_brush_data: WgpuBuffer::new(device, "tileink wgpu canvas draw brush data"),
            draw_brush_params: WgpuBuffer::new(device, "tileink wgpu canvas draw brush params"),
            draw_brush_payloads: WgpuBuffer::new(device, "tileink wgpu canvas draw brush payloads"),
            text_run_starts: WgpuBuffer::new(device, "tileink wgpu canvas text run starts"),
            text_run_counts: WgpuBuffer::new(device, "tileink wgpu canvas text run counts"),
            glyph_image_ids: WgpuBuffer::new(device, "tileink wgpu canvas glyph image ids"),
            glyph_x: WgpuBuffer::new(device, "tileink wgpu canvas glyph x"),
            glyph_y: WgpuBuffer::new(device, "tileink wgpu canvas glyph y"),
            glyph_image_left: WgpuBuffer::new(device, "tileink wgpu canvas glyph image left"),
            glyph_image_top: WgpuBuffer::new(device, "tileink wgpu canvas glyph image top"),
            glyph_image_width: WgpuBuffer::new(device, "tileink wgpu canvas glyph image width"),
            glyph_image_height: WgpuBuffer::new(device, "tileink wgpu canvas glyph image height"),
            glyph_image_content: WgpuBuffer::new(device, "tileink wgpu canvas glyph image content"),
            glyph_image_data_offsets: WgpuBuffer::new(
                device,
                "tileink wgpu canvas glyph image data offsets",
            ),
            glyph_image_data: WgpuBuffer::new(device, "tileink wgpu canvas glyph image data"),
            glyph_atlas_signature: AtlasSignature::default(),
        }
    }
}
