#ifndef TILEINK_HLSL_COARSE_TILE_CLASSIFICATION_HLSLI_INCLUDED
#define TILEINK_HLSL_COARSE_TILE_CLASSIFICATION_HLSLI_INCLUDED

#include "tags.hlsli"

uint classify_tile_flags(uint flags) {
    if ((flags & CHUNK_CLASS_OTHER) != 0u) return TILE_KIND_INTERPRETER;
    if ((flags & CHUNK_CLASS_SDF) != 0u) return (flags & CHUNK_CLASS_COLOR) != 0u ? TILE_KIND_MIXED : TILE_KIND_SDF;
    return (flags & CHUNK_CLASS_COLOR) != 0u ? TILE_KIND_COLOR : TILE_KIND_EMPTY;
}

#endif // TILEINK_HLSL_COARSE_TILE_CLASSIFICATION_HLSLI_INCLUDED
