// Shared production filter uniform. Native reflection checks each host field type and offset.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct FilterConfig {
    pub width: u32,
    pub height: u32,
    pub tiles_width: u32,
    pub tiles_height: u32,
    pub region_x0: u32,
    pub region_y0: u32,
    pub region_width: u32,
    pub region_height: u32,
    pub pixel_count: u32,
    pub active_tile_count: u32,
    pub compact_tiles: u32,
    pub dispatch_width: u32,
    /// Positive zero supplied at runtime to preserve shader product rounding.
    /// Literal-zero folding can reassociate filter recurrences and fused dots.
    pub rounding_zero: f32,
    pub downsample: u32,
    pub downsample_filter: u32,
    pub upsample_filter: u32,
    pub downsample_pad: u32,
    pub source_x0: u32,
    pub source_y0: u32,
    pub source_x1: u32,
    pub source_y1: u32,
    pub layer_stack_start: u32,
    pub layer_stack_end: u32,
    pub draw_ix: u32,
    pub mask_enabled: u32,
    pub blend_mode: u32,
    pub mask_kind: u32,
    pub clear_color: u32,
    pub filter_kind: u32,
    pub table_index: u32,
    pub brush_offset: u32,
    pub paint_sdf_shadow_base: u32,
    pub offset_x: i32,
    pub offset_y: i32,
    pub morphology_radius: u32,
    pub morphology_operator: u32,
    pub morphology_axis: u32,
    pub blur_axis: u32,
    pub kernel_offset: u32,
    pub kernel_columns: u32,
    pub kernel_rows: u32,
    pub kernel_target_x: u32,
    pub kernel_target_y: u32,
    pub kernel_edge_mode: u32,
    pub kernel_preserve_alpha: u32,
    pub lighting_output_kind: u32,
    pub surface_origin_x: i32,
    pub surface_origin_y: i32,
    pub light_kind: u32,
    pub amount: f32,
    pub rect_x0: f32,
    pub rect_y0: f32,
    pub rect_x1: f32,
    pub rect_y1: f32,
    pub radius_top_left: f32,
    pub radius_top_right: f32,
    pub radius_bottom_left: f32,
    pub radius_bottom_right: f32,
    pub surface_scale: f32,
    pub light_constant: f32,
    pub specular_exponent: f32,
    pub light_r: f32,
    pub light_g: f32,
    pub light_b: f32,
    pub light_p0: f32,
    pub light_p1: f32,
    pub light_p2: f32,
    pub light_p3: f32,
    pub light_p4: f32,
    pub light_p5: f32,
    pub light_p6: f32,
    pub light_p7: f32,
    pub light_p8: f32,
    pub turbulence_base_frequency_x: f32,
    pub turbulence_base_frequency_y: f32,
    pub turbulence_num_octaves: u32,
    pub turbulence_stitch_tiles: u32,
    pub turbulence_kind: u32,
    /// Color-space selector for SVG filter primitives (0=sRGB, 1=linear RGB).
    pub linear_rgb: u32,
    pub turbulence_pad0: u32,
    pub turbulence_pad1: u32,
    pub turbulence_transform_x: f32,
    pub turbulence_transform_y: f32,
    pub turbulence_scale_x: f32,
    pub turbulence_scale_y: f32,
    pub turbulence_tile_x: f32,
    pub turbulence_tile_y: f32,
    pub turbulence_tile_width: f32,
    pub turbulence_tile_height: f32,
    pub liquid_tint_r: f32,
    pub liquid_tint_g: f32,
    pub liquid_tint_b: f32,
    pub liquid_tint_a: f32,
    pub liquid_refraction_thickness: f32,
    pub liquid_refraction_factor: f32,
    pub liquid_refraction_dispersion: f32,
    pub liquid_fresnel_range: f32,
    pub liquid_fresnel_hardness: f32,
    pub liquid_fresnel_factor: f32,
    pub liquid_glare_range: f32,
    pub liquid_glare_hardness: f32,
    pub liquid_glare_convergence: f32,
    pub liquid_glare_opposite_factor: f32,
    pub liquid_glare_factor: f32,
    pub liquid_glare_angle: f32,
    pub matrix_pad0: u32,
    pub matrix_pad1: u32,
    pub matrix_pad2: u32,
    pub matrix_r: [f32; 4],
    pub matrix_g: [f32; 4],
    pub matrix_b: [f32; 4],
    pub matrix_a: [f32; 4],
    pub matrix_bias: [f32; 4],
}

impl Default for FilterConfig {
    fn default() -> Self {
        Self {
            width: 0,
            height: 0,
            tiles_width: 0,
            tiles_height: 0,
            region_x0: 0,
            region_y0: 0,
            region_width: 0,
            region_height: 0,
            pixel_count: 0,
            active_tile_count: 0,
            compact_tiles: 0,
            dispatch_width: 0,
            rounding_zero: 0.0,
            downsample: 1,
            downsample_filter: 0,
            upsample_filter: 0,
            downsample_pad: 0,
            source_x0: 0,
            source_y0: 0,
            source_x1: 0,
            source_y1: 0,
            layer_stack_start: 0,
            layer_stack_end: 0,
            draw_ix: 0,
            mask_enabled: 0,
            blend_mode: 0,
            mask_kind: 0,
            clear_color: 0,
            filter_kind: 0,
            table_index: 0,
            brush_offset: 0,
            paint_sdf_shadow_base: 0,
            offset_x: 0,
            offset_y: 0,
            morphology_radius: 0,
            morphology_operator: 0,
            morphology_axis: 0,
            blur_axis: 0,
            kernel_offset: 0,
            kernel_columns: 0,
            kernel_rows: 0,
            kernel_target_x: 0,
            kernel_target_y: 0,
            kernel_edge_mode: 0,
            kernel_preserve_alpha: 0,
            lighting_output_kind: 0,
            surface_origin_x: 0,
            surface_origin_y: 0,
            light_kind: 0,
            amount: 0.0,
            rect_x0: 0.0,
            rect_y0: 0.0,
            rect_x1: 0.0,
            rect_y1: 0.0,
            radius_top_left: 0.0,
            radius_top_right: 0.0,
            radius_bottom_left: 0.0,
            radius_bottom_right: 0.0,
            surface_scale: 0.0,
            light_constant: 0.0,
            specular_exponent: 0.0,
            light_r: 0.0,
            light_g: 0.0,
            light_b: 0.0,
            light_p0: 0.0,
            light_p1: 0.0,
            light_p2: 0.0,
            light_p3: 0.0,
            light_p4: 0.0,
            light_p5: 0.0,
            light_p6: 0.0,
            light_p7: 0.0,
            light_p8: 0.0,
            turbulence_base_frequency_x: 0.0,
            turbulence_base_frequency_y: 0.0,
            turbulence_num_octaves: 0,
            turbulence_stitch_tiles: 0,
            turbulence_kind: 0,
            linear_rgb: 0,
            turbulence_pad0: 0,
            turbulence_pad1: 0,
            turbulence_transform_x: 0.0,
            turbulence_transform_y: 0.0,
            turbulence_scale_x: 0.0,
            turbulence_scale_y: 0.0,
            turbulence_tile_x: 0.0,
            turbulence_tile_y: 0.0,
            turbulence_tile_width: 0.0,
            turbulence_tile_height: 0.0,
            liquid_tint_r: 0.0,
            liquid_tint_g: 0.0,
            liquid_tint_b: 0.0,
            liquid_tint_a: 0.0,
            liquid_refraction_thickness: 0.0,
            liquid_refraction_factor: 0.0,
            liquid_refraction_dispersion: 0.0,
            liquid_fresnel_range: 0.0,
            liquid_fresnel_hardness: 0.0,
            liquid_fresnel_factor: 0.0,
            liquid_glare_range: 0.0,
            liquid_glare_hardness: 0.0,
            liquid_glare_convergence: 0.0,
            liquid_glare_opposite_factor: 0.0,
            liquid_glare_factor: 0.0,
            liquid_glare_angle: 0.0,
            matrix_pad0: 0,
            matrix_pad1: 0,
            matrix_pad2: 0,
            matrix_r: [0.0; 4],
            matrix_g: [0.0; 4],
            matrix_b: [0.0; 4],
            matrix_a: [0.0; 4],
            matrix_bias: [0.0; 4],
        }
    }
}
