use super::region;
use crate::{
    native::runtime::{
        Result,
        compute::{ComputeBatch, ResourceId},
    },
    shared::{
        draw_record::DrawRecord, filter_config::FilterConfig, gpu_sdf::encoded_sdf,
        line_seg::LineSegment, path::PathRecord, tile_seg_range::TileSegmentRange,
    },
};

/// Immutable scene geometry whose raw shader addresses have been checked before upload.
/// Scan-produced geometry will enter through its stage-owned allocation contract.
#[derive(Clone, Copy)]
pub struct Geometry {
    bindings: [(u32, ResourceId); 6],
    shadow_base: u32,
    draw_count: u32,
}

/// Logical scene slices; allocation padding is never part of these domains.
#[derive(Default)]
pub struct Scene<'a> {
    pub draws: &'a [DrawRecord],
    pub paths: &'a [PathRecord],
    pub backdrops: &'a [i32],
    pub ranges: &'a [TileSegmentRange],
    pub segments: &'a [LineSegment],
    pub paint: &'a [u32],
    pub shadow_base: u32,
}

impl Geometry {
    /// Bind geometry already generated by scan, without a CPU round trip.
    /// # Safety
    /// All handles must belong to one batch. Scan must precede every consumer;
    /// draw/path/paint records and scan capacities must cover the logical scene.
    pub(in crate::native::runtime::program) unsafe fn from_scan(
        draws: ResourceId,
        scan: &crate::native::runtime::program::scene_scan::ScanOutput,
        paint: ResourceId,
        draw_count: u32,
        shadow_base: u32,
    ) -> Self {
        Self {
            bindings: [
                (20, draws),
                (21, scan.paths),
                (22, scan.backdrops),
                (23, scan.tile_segment_ranges),
                (24, scan.segments),
                (10, paint),
            ],
            shadow_base,
            draw_count,
        }
    }

    pub(super) fn bindings(&self) -> &[(u32, ResourceId)] {
        &self.bindings
    }
    pub(super) fn shadow_base(&self) -> u32 {
        self.shadow_base
    }
    pub(super) fn draw_count(&self) -> u32 {
        self.draw_count
    }

    pub fn upload(batch: &mut ComputeBatch, scene: Scene<'_>) -> Result<Self> {
        let Scene {
            draws,
            paths,
            backdrops,
            ranges,
            segments,
            paint,
            shadow_base,
        } = scene;
        if backdrops.len() != ranges.len() {
            return Err("layer backdrop/range lengths differ".into());
        }
        for range in ranges {
            if range.start > range.end || range.end as usize > segments.len() {
                return Err("layer segment range exceeds geometry".into());
            }
        }
        for path in paths {
            let width = path
                .tile_x1
                .checked_sub(path.tile_x0)
                .ok_or("reversed layer path bounds")?;
            let height = path
                .tile_y1
                .checked_sub(path.tile_y0)
                .ok_or("reversed layer path bounds")?;
            let count = u64::from(width) * u64::from(height);
            // Check the logical path span before its enclosing buffer capacity.
            // Otherwise valid allocation padding becomes live tile geometry.
            if count > u64::from(path.data_len)
                || u64::from(path.data_offset) + u64::from(path.data_len) > ranges.len() as u64
            {
                return Err("layer path tile range exceeds geometry".into());
            }
        }
        for segment in segments {
            if bytemuck::cast_slice::<LineSegment, f32>(std::slice::from_ref(segment))
                .iter()
                .any(|value| !value.is_finite())
            {
                return Err("nonfinite layer segment".into());
            }
        }
        for draw in draws {
            if bytemuck::cast_slice::<_, f32>(std::slice::from_ref(&draw.inverse_transform))
                .iter()
                .any(|value| !value.is_finite())
            {
                return Err("nonfinite layer inverse transform".into());
            }
            for (offset, len, base) in [
                (draw.sdf_offset, draw.sdf_len, 0),
                (draw.sdf_shadow_offset, draw.sdf_shadow_len, shadow_base),
            ] {
                if offset == u32::MAX {
                    continue;
                }
                let offset = base
                    .checked_add(offset)
                    .ok_or("layer shape offset overflow")?;
                let sdf = encoded_sdf(paint, offset, len).ok_or("invalid layer shape record")?;
                if sdf
                    .coords
                    .iter()
                    .chain(&sdf.radii)
                    .chain(&sdf.stroke)
                    .chain(&sdf.shadow)
                    .any(|v| !v.is_finite())
                {
                    return Err("invalid layer shape parameters".into());
                }
            }
        }
        let inputs: [(u32, &[u8]); 6] = [
            (20, bytemuck::cast_slice(draws)),
            (21, bytemuck::cast_slice(paths)),
            (22, bytemuck::cast_slice(backdrops)),
            (23, bytemuck::cast_slice(ranges)),
            (24, bytemuck::cast_slice(segments)),
            (10, bytemuck::cast_slice(paint)),
        ];
        let mut bindings = Vec::new();
        let minima = [
            std::mem::size_of::<DrawRecord>(),
            std::mem::size_of::<PathRecord>(),
            4,
            std::mem::size_of::<TileSegmentRange>(),
            std::mem::size_of::<LineSegment>(),
            4,
        ];
        for ((slot, bytes), minimum) in inputs.into_iter().zip(minima) {
            if bytes.len() > u32::MAX as usize {
                return Err("layer raw address capacity overflow".into());
            }
            bindings.push((
                slot,
                batch.buffer(if bytes.is_empty() {
                    vec![0; minimum]
                } else {
                    bytes.to_vec()
                })?,
            ));
        }
        Ok(Self {
            bindings: bindings.try_into().unwrap(),
            shadow_base,
            draw_count: u32::try_from(draws.len())?,
        })
    }
    pub fn mask(
        &self,
        batch: &mut ComputeBatch,
        mut config: FilterConfig,
        tiles: Option<&[u32]>,
        target: ResourceId,
    ) -> Result<()> {
        if config.width > i32::MAX as u32 || config.height > i32::MAX as u32 {
            return Err("layer pixel coordinates exceed signed range".into());
        }
        config.paint_sdf_shadow_base = self.shadow_base;
        if config.draw_ix >= self.draw_count {
            config.draw_ix = u32::MAX;
        }
        region::record(
            batch,
            "filter_layer_mask_region",
            region::Geometry::Pixels,
            config,
            tiles,
            region::ReadBindings {
                buffers: &self.bindings,
                ..Default::default()
            },
            target,
        )
    }
}
