use super::*;
#[derive(Clone, Copy, Debug)]
pub(crate) enum ColorFilterKind {
    Brightness,
    Contrast,
    Grayscale,
    HueRotate,
    Invert,
    Opacity,
    Saturate,
    Sepia,
}
#[derive(Debug)]
pub(crate) enum FilterKernel<'a> {
    ClearRenderTarget {
        target: RenderTargetId,
        color: u32,
    },
    ClearRenderRegion {
        target: RenderTargetId,
        bounds: Bounds,
        color: u32,
    },
    FloodRegionToTarget {
        target: RenderTargetId,
        bounds: Bounds,
        brush_offset: u32,
    },
    BuildDropShadowMaskToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        dx: i32,
        dy: i32,
    },
    SourceAlphaToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
    },
    SourceOverFilterInput {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
    },
    BlendFilterInputs {
        input1: RenderTargetId,
        input2: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        mode: Mix,
    },
    CompositeFilterInputs {
        input1: RenderTargetId,
        input2: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        operator: filter_model::CompositeOperator,
    },
    DisplacementMapFilterInputs {
        input1: RenderTargetId,
        input2: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        displacement: &'a filter_model::DisplacementMap,
    },
    TurbulenceToTarget {
        target: RenderTargetId,
        bounds: Bounds,
        turbulence: &'a filter_model::Turbulence,
        table_index: u32,
    },
    TileFilterInput {
        input: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        source_region: Bounds,
    },
    CompositeDropShadowToTarget {
        target: RenderTargetId,
        shadow: RenderTargetId,
        bounds: Bounds,
        brush_offset: u32,
    },
    ApplyColorMatrixToTarget {
        target: RenderTargetId,
        bounds: Bounds,
        matrix: [f32; 20],
    },
    ApplyComponentTransferToTarget {
        target: RenderTargetId,
        bounds: Bounds,
        table_index: u32,
    },
    ConvolveMatrixToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        matrix: &'a filter_model::ConvolveMatrix,
        kernel_offset: u32,
    },
    DiffuseLightingToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        lighting: &'a filter_model::DiffuseLighting,
    },
    SpecularLightingToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        lighting: &'a filter_model::SpecularLighting,
    },
    LiquidGlassToTarget {
        source: RenderTargetId,
        blurred: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        glass: filter_model::RectLiquidGlass,
        region: filter_model::RectLiquidGlassRegion,
    },
    BlurRegionToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        std_dev: f32,
        axis: u32,
    },
    BlurRegionPartialToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        output_bounds: Bounds,
        sample_bounds: Bounds,
        std_dev: f32,
        axis: u32,
    },
    MorphologyAxisToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        radius: u32,
        operator: filter_model::MorphologyOperator,
        axis: u32,
    },
    OffsetRegionToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        dx: i32,
        dy: i32,
    },
    CopyRegionToTarget {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
    },
    ApplyColorFilterToTarget {
        target: RenderTargetId,
        bounds: Bounds,
        kind: ColorFilterKind,
        amount: f32,
    },
    DownsampleRegion {
        source: RenderTargetId,
        target: RenderTargetId,
        source_bounds: Bounds,
        low_bounds: Bounds,
        sampling: filter_model::BlurSampling,
    },
    UpsampleRegion {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        low_bounds: Bounds,
        sampling: filter_model::BlurSampling,
    },
    UpsampleRectCompositeRegion {
        source: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        low_bounds: Bounds,
        sampling: filter_model::BlurSampling,
        region: &'a crate::shared::layer::region::Region,
    },
    RectLiquidGlassCompositeRegion {
        source: RenderTargetId,
        blurred: RenderTargetId,
        target: RenderTargetId,
        bounds: Bounds,
        blurred_bounds: Bounds,
        sampling: filter_model::BlurSampling,
        glass: filter_model::RectLiquidGlass,
        region: filter_model::RectLiquidGlassRegion,
    },
}
