#ifndef TILEINK_HLSL_FINE_TEXT_CONSTANTS_INCLUDED
#define TILEINK_HLSL_FINE_TEXT_CONSTANTS_INCLUDED

// Shared perceptual text parameters; the WGSL build imports these exact literals.
static const float TEXT_DARK_ON_LIGHT_COVERAGE_STRENGTH = 0.95;
static const float TEXT_DARK_ON_LIGHT_LUMA_BASE = 1.5728465;
static const float TEXT_DARK_ON_LIGHT_LUMA_TAPER = 1.15;
static const float TEXT_DARK_ON_LIGHT_CHROMA_BOOST = 0.3656558;
static const float TEXT_DARK_ON_LIGHT_CORE_CONTRAST = 0.8;
static const float TEXT_SOURCE_CHROMA_COVERAGE_BOOST = 0.0;
static const float TEXT_SOURCE_CHROMA_COVERAGE_CONTRAST_LIMIT = 0.23100804;
static const float TEXT_LIGHT_ON_DARK_COVERAGE_REDUCTION = 0.20662805;
static const float TEXT_LIGHT_ON_DARK_BLACK_LUMA_LIMIT = 0.02875403;
static const float TEXT_LIGHT_ON_DARK_CHROMA_REDUCTION = 0.11479953;
static const float TEXT_LIGHT_ON_DARK_HIGH_LUMA_CHROMA_REDUCTION = 0.4492354;
static const float TEXT_LIGHT_ON_DARK_HIGH_LUMA_THRESHOLD = 0.26129702;
static const float TEXT_LIGHT_ON_COLORED_DARK_CHROMA_REDUCTION = 0.48728964;
static const float TEXT_LIGHT_ON_COLORED_DARK_LUMA_LIMIT = 0.11519971;
static const float TEXT_ALPHA_MASK_CHROMA_SCALE = 1.3566802;
static const float TEXT_SUBPIXEL_MASK_CHROMA_SCALE = 0.9483659;
static const float TEXT_ALPHA_MASK_APPARENT_AXIS_STRENGTH = 1.036124;
static const float TEXT_ALPHA_MASK_APPARENT_AXIS_LUMA_LIMIT = 0.6887328;
static const float TEXT_SUBPIXEL_MASK_APPARENT_AXIS_STRENGTH = 1.447765;
static const float TEXT_SUBPIXEL_MASK_APPARENT_AXIS_LUMA_LIMIT = 0.1682842;
static const float TEXT_ALPHA_MASK_LOW_LUMA_CHROMA_REDUCTION = 0.41302064;
static const float TEXT_ALPHA_MASK_LOW_LUMA_CONTRAST_LIMIT = 0.10123872;
static const float TEXT_SUBPIXEL_MASK_LOW_LUMA_CHROMA_REDUCTION = 0.0;
static const float TEXT_SUBPIXEL_MASK_LOW_LUMA_CONTRAST_LIMIT = 0.06385561;

#endif
