#ifndef TILEINK_RANGE_SCATTER_CONSTANTS_INCLUDED
#define TILEINK_RANGE_SCATTER_CONSTANTS_INCLUDED

static const uint RANGE_SCATTER_HEADER_WORDS = 4u;
static const uint RANGE_SCATTER_DESCRIPTOR_WORDS = 4u;

#endif
